//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitsPlannerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgendaItemsNotification
    {
        public int AgendaItemId { get; set; }
        public int NotificationId { get; set; }
        public Nullable<System.DateTime> TimeOfNotification { get; set; }
    
        public virtual AgendaItem AgendaItem { get; set; }
        public virtual NotificationPreference NotificationPreference { get; set; }
    }
}
