//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitsPlannerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgendaItem
    {
        public AgendaItem()
        {
            this.AgendaItemsNotifications = new HashSet<AgendaItemsNotification>();
            this.EmployeesAgendaItems = new HashSet<EmployeesAgendaItem>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int VisitId { get; set; }
        public int LocationId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int VisitTypeId { get; set; }
        public string Outcome { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Visit Visit { get; set; }
        public virtual VisitType VisitType { get; set; }
        public virtual ICollection<AgendaItemsNotification> AgendaItemsNotifications { get; set; }
        public virtual ICollection<EmployeesAgendaItem> EmployeesAgendaItems { get; set; }
    }
}
