//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitsPlannerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesAgendaItem
    {
        public int EmployeeId { get; set; }
        public int AgendaItemId { get; set; }
        public bool IsResponsable { get; set; }
    
        public virtual AgendaItem AgendaItem { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
