//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitsPlannerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.NotificationPreferences = new HashSet<NotificationPreference>();
            this.EmployeesAgendaItems = new HashSet<EmployeesAgendaItem>();
            this.Visits = new HashSet<Visit>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> Role { get; set; }
    
        public virtual ICollection<NotificationPreference> NotificationPreferences { get; set; }
        public virtual ICollection<EmployeesAgendaItem> EmployeesAgendaItems { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
