//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitsPlannerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitType
    {
        public VisitType()
        {
            this.AgendaItems = new HashSet<AgendaItem>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<AgendaItem> AgendaItems { get; set; }
    }
}
